all = 'All '
work = 'work '
as_well_as = 'and '
nyet = 'no '
asobo = 'play '
creates = 'makes '
name = 'Jack '
single = 'a '
boring = 'dull '
male_child = 'boy'
period = '.'
print(all+work+as_well_as+nyet+asobo+creates+name+single+boring+male_child+period)
